# Generated by Django 6.1.1 on 2026-09-24 19:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('type', models.CharField(choices=[('COUNTRY', 'Country'), ('MONTH', 'Month'), ('LANGUAGE', 'Language'), ('CURRENCY', 'Currency'), ('TIMEZONE', 'Timezone'), ('AGE_RANGE', 'Age range'), ('CUSTOM', 'Custom')], db_index=True, default='CUSTOM', max_length=24)),
                ('is_system', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'q_system_lists',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='covers/')),
                ('category', models.CharField(blank=True, db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('CLOSED', 'Closed'), ('ARCHIVED', 'Archived')], db_index=True, default='DRAFT', max_length=16)),
                ('visibility', models.CharField(choices=[('PUBLIC', 'Public'), ('ASSIGNED', 'Assigned')], db_index=True, default='ASSIGNED', max_length=16)),
                ('response_mode', models.CharField(choices=[('IDENTIFIED', 'Identified'), ('ANONYMOUS', 'Anonymous')], db_index=True, default='IDENTIFIED', max_length=16)),
                ('estimated_time_minutes', models.PositiveIntegerField(default=0, help_text='Estimated time in minutes')),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_surveys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'q_surveys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('SHORT_TEXT', 'Short text'), ('LONG_TEXT', 'Long text'), ('EMAIL', 'Email'), ('PHONE', 'Phone'), ('URL', 'URL'), ('NUMBER', 'Number'), ('RATING', 'Rating'), ('LINEAR_SCALE', 'Linear scale'), ('NPS', 'NPS'), ('SLIDER', 'Slider'), ('SINGLE_CHOICE', 'Single choice'), ('MULTIPLE_CHOICE', 'Multiple choice'), ('DROPDOWN', 'Dropdown'), ('YES_NO', 'Yes / No'), ('LIKERT', 'Likert'), ('RANKING', 'Ranking'), ('DATE', 'Date'), ('TIME', 'Time'), ('DATETIME', 'Datetime'), ('MATRIX', 'Matrix'), ('FILE_UPLOAD', 'File upload'), ('TEXT_BLOCK', 'Text block'), ('SECTION', 'Section')], db_index=True, max_length=24)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('required', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='q_surveys.survey')),
                ('system_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='q_surveys.systemlist')),
            ],
            options={
                'db_table': 'q_questions',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('system_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='q_surveys.systemlist')),
            ],
            options={
                'db_table': 'q_list_items',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MatrixRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matrix_rows', to='q_surveys.question')),
            ],
            options={
                'db_table': 'q_matrix_rows',
                'ordering': ['order'],
                'indexes': [models.Index(fields=['question', 'order'], name='q_matrix_ro_questio_3f1bf1_idx')],
            },
        ),
        migrations.CreateModel(
            name='MatrixColumn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matrix_columns', to='q_surveys.question')),
            ],
            options={
                'db_table': 'q_matrix_columns',
                'ordering': ['order'],
                'indexes': [models.Index(fields=['question', 'order'], name='q_matrix_co_questio_a82a10_idx')],
                'constraints': [models.UniqueConstraint(fields=('question', 'value'), name='uniq_matrix_col_value_per_question')],
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='q_surveys.question')),
            ],
            options={
                'db_table': 'q_question_options',
                'ordering': ['order'],
                'indexes': [models.Index(fields=['question', 'order'], name='q_question__questio_95c546_idx')],
                'constraints': [models.UniqueConstraint(fields=('question', 'value'), name='uniq_option_value_per_question')],
            },
        ),
        migrations.AddIndex(
            model_name='survey',
            index=models.Index(fields=['created_by', 'status'], name='q_surveys_created_f690c3_idx'),
        ),
        migrations.AddIndex(
            model_name='survey',
            index=models.Index(fields=['status', 'visibility', 'created_at'], name='q_surveys_status_d77141_idx'),
        ),
        migrations.AddIndex(
            model_name='survey',
            index=models.Index(fields=['published_at'], name='q_surveys_publish_5a9fe9_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['survey', 'order'], name='q_questions_survey__a01071_idx'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('survey', 'order'), name='uniq_question_order_per_survey'),
        ),
        migrations.AddIndex(
            model_name='listitem',
            index=models.Index(fields=['system_list', 'order'], name='q_list_item_system__e990dc_idx'),
        ),
    ]
