# Generated by Django 6.1.1 on 2026-09-24 20:55

import django.db.models.constraints
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('q_surveys', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='question',
            name='uniq_question_order_per_survey',
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('survey', 'order'), name='uniq_question_order_per_survey'),
        ),
    ]
