# Generated by Django 6.1.1 on 2026-09-25 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('q_surveys', '0002_remove_question_uniq_question_order_per_survey_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='question',
            new_name='q_questions_survey_order_idx',
            old_name='q_questions_survey__a01071_idx',
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['order', 'survey'], name='q_questions_order_survey_idx'),
        ),
    ]
