# Generated by Django 6.1.1 on 2026-09-24 19:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('q_surveys', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('OVERDUE', 'Overdue')], db_index=True, default='PENDING', max_length=16)),
                ('assigned_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('allow_resume', models.BooleanField(default=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_made', to=settings.AUTH_USER_MODEL)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='q_surveys.survey')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'q_survey_assignments',
                'ordering': ['-assigned_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='q_survey_as_user_id_de6f68_idx'), models.Index(fields=['survey', 'status'], name='q_survey_as_survey__cf553e_idx'), models.Index(fields=['due_date', 'status'], name='q_survey_as_due_dat_6f2647_idx')],
                'constraints': [models.UniqueConstraint(fields=('survey', 'user'), name='uniq_assignment_per_user_survey')],
            },
        ),
    ]
