FROM node:20-alpine

WORKDIR /app

RUN apk add --no-cache libc6-compat

COPY package.json package-lock.json* ./
RUN npm install

COPY . .

EXPOSE 3000
ENV PORT=3000
ENV WATCHPACK_POLLING=true

CMD ["npm", "run", "dev"]