FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1 \
    PIP_DISABLE_PIP_VERSION_CHECK=1

WORKDIR /app

# RUN apt-get update -o Acquire::Retries=5 && \
#     apt-get install -y --no-install-recommends \
#         build-essential \
#         libpq-dev \
#         curl \
#         netcat-openbsd \
#     && rm -rf /var/lib/apt/lists/*

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        libpq-dev \
        netcat-openbsd \
    && rm -rf /var/lib/apt/lists/*

COPY requirements /app/requirements
RUN pip install -r /app/requirements/development.txt

COPY . /app

RUN chmod +x /app/entrypoint.sh

EXPOSE 8000

ENTRYPOINT ["/app/entrypoint.sh"]
CMD ["gunicorn", "config.wsgi:application", \
     "--bind", "0.0.0.0:8000", \
     "--workers", "2", \
     "--reload", \
     "--reload-engine", "auto", \
     "--access-logfile", "-", \
     "--error-logfile", "-", \
     "--log-level", "info"]