# Generated by Django 6.1.1 on 2026-09-24 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('q_accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='emailverificationtoken',
            new_name='q_email_ver_user_id_e246e5_idx',
            old_name='q_accounts__user_id_06d94c_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='q_users_is_acti_251039_idx',
            old_name='q_accounts__is_acti_71ddbe_idx',
        ),
        migrations.AlterModelTable(
            name='emailverificationtoken',
            table='q_email_verification_tokens',
        ),
        migrations.AlterModelTable(
            name='user',
            table='q_users',
        ),
    ]
