# Generated by Django 6.1.1 on 2026-09-25 10:26

import apps.q_accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('q_accounts', '0002_rename_q_accounts__user_id_06d94c_idx_q_email_ver_user_id_e246e5_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notification_preferences',
            field=models.JSONField(blank=True, default=apps.q_accounts.models.default_notification_preferences),
        ),
    ]
