# Generated by Django 6.1.1 on 2026-09-24 19:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('q_assignments', '0001_initial'),
        ('q_surveys', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted')], db_index=True, default='DRAFT', max_length=16)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('completion_time', models.DurationField(blank=True, null=True)),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responses', to='q_assignments.surveyassignment')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='q_surveys.survey')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'q_survey_responses',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.JSONField(default=dict)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='q_surveys.question')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='q_responses.surveyresponse')),
            ],
            options={
                'db_table': 'q_answers',
            },
        ),
        migrations.CreateModel(
            name='AnswerFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='answer_files/%Y/%m/')),
                ('original_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('size', models.PositiveIntegerField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='q_responses.answer')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_files', to='q_surveys.survey')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_answer_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'q_answer_files',
                'ordering': ['order', 'created_at'],
                'indexes': [models.Index(fields=['answer'], name='q_answer_fi_answer__33ae59_idx'), models.Index(fields=['survey', 'uploaded_by'], name='q_answer_fi_survey__109551_idx'), models.Index(fields=['answer', 'order'], name='q_answer_fi_answer__756c72_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='surveyresponse',
            index=models.Index(fields=['user'], name='q_survey_re_user_id_a013e9_idx'),
        ),
        migrations.AddIndex(
            model_name='surveyresponse',
            index=models.Index(fields=['survey'], name='q_survey_re_survey__ced221_idx'),
        ),
        migrations.AddIndex(
            model_name='surveyresponse',
            index=models.Index(fields=['submitted_at'], name='q_survey_re_submitt_e741e6_idx'),
        ),
        migrations.AddIndex(
            model_name='surveyresponse',
            index=models.Index(fields=['status'], name='q_survey_re_status_e7696e_idx'),
        ),
        migrations.AddConstraint(
            model_name='surveyresponse',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('survey', 'user'), name='uniq_response_per_user_survey'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['response'], name='q_answers_respons_2cea26_idx'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['question'], name='q_answers_questio_9c3e43_idx'),
        ),
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(fields=('response', 'question'), name='uniq_answer_per_question'),
        ),
    ]
